import { Movie, MovieRow } from '@/types/movie';

// ─────────────────────────────────────────────────────────────────────────────
// MOCK MOVIE DATA
// Uses real TMDB CDN image paths for popular well-known movies.
// Each movie carries all ML-relevant fields: genres, cast, director, keywords.
// When the backend is ready, replace MOCK_MOVIES with API responses.
// ─────────────────────────────────────────────────────────────────────────────

export const MOCK_MOVIES: Movie[] = [
  {
    id: 27205,
    title: 'Inception',
    overview: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
    poster_path: '/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg',
    backdrop_path: '/s3TBrRGB1iav7gFOCNx3H31MoES.jpg',
    release_date: '2010-07-16',
    vote_average: 8.4,
    vote_count: 35000,
    genre_ids: [28, 878, 53],
    genres: [{ id: 28, name: 'Action' }, { id: 878, name: 'Sci-Fi' }, { id: 53, name: 'Thriller' }],
    runtime: 148,
    director: 'Christopher Nolan',
    cast: [
      { id: 6193, name: 'Leonardo DiCaprio', character: 'Cobb' },
      { id: 27578, name: 'Joseph Gordon-Levitt', character: 'Arthur' },
      { id: 1373737, name: 'Elliot Page', character: 'Ariadne' },
    ],
    keywords: ['dream', 'heist', 'subconscious', 'mind', 'thriller'],
    maturity_rating: 'PG-13',
  },
  {
    id: 155,
    title: 'The Dark Knight',
    overview: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
    poster_path: '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    backdrop_path: '/hkBaDkMWbLaf8B1lsWsKX7Ew3Xq.jpg',
    release_date: '2008-07-18',
    vote_average: 9.0,
    vote_count: 30000,
    genre_ids: [28, 80, 18],
    genres: [{ id: 28, name: 'Action' }, { id: 80, name: 'Crime' }, { id: 18, name: 'Drama' }],
    runtime: 152,
    director: 'Christopher Nolan',
    cast: [
      { id: 3894, name: 'Christian Bale', character: 'Bruce Wayne / Batman' },
      { id: 1810, name: 'Heath Ledger', character: 'Joker' },
    ],
    keywords: ['batman', 'joker', 'gotham', 'superhero', 'crime'],
    maturity_rating: 'PG-13',
  },
  {
    id: 238,
    title: 'The Godfather',
    overview: 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers.',
    poster_path: '/3bhkrj58Vtu7enYsLLeAvAXkgbl.jpg',
    backdrop_path: '/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
    release_date: '1972-03-24',
    vote_average: 9.2,
    vote_count: 18000,
    genre_ids: [18, 80],
    genres: [{ id: 18, name: 'Drama' }, { id: 80, name: 'Crime' }],
    runtime: 175,
    director: 'Francis Ford Coppola',
    cast: [
      { id: 1158, name: 'Marlon Brando', character: 'Vito Corleone' },
      { id: 1100, name: 'Al Pacino', character: 'Michael Corleone' },
    ],
    keywords: ['mafia', 'crime', 'family', 'power', 'italy'],
    maturity_rating: 'R',
  },
  {
    id: 603,
    title: 'The Matrix',
    overview: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
    poster_path: '/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
    backdrop_path: '/ncEsesgOJDNrTUED89hYbA117wo.jpg',
    release_date: '1999-03-31',
    vote_average: 8.7,
    vote_count: 24000,
    genre_ids: [28, 878],
    genres: [{ id: 28, name: 'Action' }, { id: 878, name: 'Sci-Fi' }],
    runtime: 136,
    director: 'Lana Wachowski',
    cast: [
      { id: 6384, name: 'Keanu Reeves', character: 'Neo' },
      { id: 2975, name: 'Laurence Fishburne', character: 'Morpheus' },
    ],
    keywords: ['simulation', 'hacker', 'virtual reality', 'cyberpunk', 'revolution'],
    maturity_rating: 'R',
  },
  {
    id: 550,
    title: 'Fight Club',
    overview: 'A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy.',
    poster_path: '/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg',
    backdrop_path: '/hZkgoQYus5vegHoetLkCJzf9lfK.jpg',
    release_date: '1999-10-15',
    vote_average: 8.8,
    vote_count: 27000,
    genre_ids: [18, 53],
    genres: [{ id: 18, name: 'Drama' }, { id: 53, name: 'Thriller' }],
    runtime: 139,
    director: 'David Fincher',
    cast: [
      { id: 287, name: 'Brad Pitt', character: 'Tyler Durden' },
      { id: 819, name: 'Edward Norton', character: 'The Narrator' },
    ],
    keywords: ['identity', 'anarchy', 'masculinity', 'underground', 'twist'],
    maturity_rating: 'R',
  },
  {
    id: 13,
    title: 'Forrest Gump',
    overview: 'The history of the United States from the 1950s to the 70s unfolds from the perspective of an Alabama man with an IQ of 75, who is determined to make something out of his life.',
    poster_path: '/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
    backdrop_path: '/qdIMHd4sEfJSckfVJfKQvisL02a.jpg',
    release_date: '1994-07-06',
    vote_average: 8.5,
    vote_count: 25000,
    genre_ids: [35, 18, 10749],
    genres: [{ id: 35, name: 'Comedy' }, { id: 18, name: 'Drama' }, { id: 10749, name: 'Romance' }],
    runtime: 142,
    director: 'Robert Zemeckis',
    cast: [
      { id: 31, name: 'Tom Hanks', character: 'Forrest Gump' },
    ],
    keywords: ['destiny', 'life', 'love', 'history', 'inspirational'],
    maturity_rating: 'PG-13',
  },
  {
    id: 120,
    title: 'The Lord of the Rings: The Fellowship of the Ring',
    overview: 'A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.',
    poster_path: '/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg',
    backdrop_path: '/pIUvQ9Ed35wlWhY2oU6OmwEsmzG.jpg',
    release_date: '2001-12-19',
    vote_average: 8.8,
    vote_count: 22000,
    genre_ids: [12, 14, 28],
    genres: [{ id: 12, name: 'Adventure' }, { id: 14, name: 'Fantasy' }, { id: 28, name: 'Action' }],
    runtime: 178,
    director: 'Peter Jackson',
    cast: [
      { id: 95, name: 'Elijah Wood', character: 'Frodo Baggins' },
      { id: 593, name: 'Ian McKellen', character: 'Gandalf' },
    ],
    keywords: ['fantasy', 'quest', 'ring', 'hobbit', 'epic'],
    maturity_rating: 'PG-13',
  },
  {
    id: 11,
    title: 'Star Wars: A New Hope',
    overview: 'Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee, and two droids to save the galaxy from the Empire\'s world-destroying battle station.',
    poster_path: '/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg',
    backdrop_path: '/zqkmTXzjkAgXmEWLRsY4UpTWCeo.jpg',
    release_date: '1977-05-25',
    vote_average: 8.6,
    vote_count: 20000,
    genre_ids: [12, 28, 878],
    genres: [{ id: 12, name: 'Adventure' }, { id: 28, name: 'Action' }, { id: 878, name: 'Sci-Fi' }],
    runtime: 121,
    director: 'George Lucas',
    cast: [
      { id: 2, name: 'Mark Hamill', character: 'Luke Skywalker' },
      { id: 3, name: 'Harrison Ford', character: 'Han Solo' },
    ],
    keywords: ['space', 'force', 'empire', 'jedi', 'galaxy'],
    maturity_rating: 'PG',
  },
  {
    id: 680,
    title: 'Pulp Fiction',
    overview: 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
    poster_path: '/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
    backdrop_path: '/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
    release_date: '1994-10-14',
    vote_average: 8.9,
    vote_count: 28000,
    genre_ids: [53, 80],
    genres: [{ id: 53, name: 'Thriller' }, { id: 80, name: 'Crime' }],
    runtime: 154,
    director: 'Quentin Tarantino',
    cast: [
      { id: 287, name: 'Brad Pitt', character: 'Vincent Vega' },
      { id: 234, name: 'Samuel L. Jackson', character: 'Jules Winnfield' },
    ],
    keywords: ['nonlinear', 'crime', 'dialogue', 'violence', 'hitman'],
    maturity_rating: 'R',
  },
  {
    id: 475557,
    title: 'Joker',
    overview: 'In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime. This path brings him face-to-face with his alter-ego: the Joker.',
    poster_path: '/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg',
    backdrop_path: '/n6bUvigpRFqSwmPp1ZqkLtCAoDh.jpg',
    release_date: '2019-10-04',
    vote_average: 8.2,
    vote_count: 22000,
    genre_ids: [80, 53, 18],
    genres: [{ id: 80, name: 'Crime' }, { id: 53, name: 'Thriller' }, { id: 18, name: 'Drama' }],
    runtime: 122,
    director: 'Todd Phillips',
    cast: [
      { id: 380, name: 'Joaquin Phoenix', character: 'Arthur Fleck / Joker' },
    ],
    keywords: ['villain', 'mental illness', 'gotham', 'chaos', 'society'],
    maturity_rating: 'R',
  },
  {
    id: 1667,
    title: 'Interstellar',
    overview: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
    poster_path: '/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    backdrop_path: '/xJHokMbljvjADYdit5fK5VQsXEG.jpg',
    release_date: '2014-11-05',
    vote_average: 8.6,
    vote_count: 31000,
    genre_ids: [12, 18, 878],
    genres: [{ id: 12, name: 'Adventure' }, { id: 18, name: 'Drama' }, { id: 878, name: 'Sci-Fi' }],
    runtime: 169,
    director: 'Christopher Nolan',
    cast: [
      { id: 37645, name: 'Matthew McConaughey', character: 'Cooper' },
      { id: 3234, name: 'Anne Hathaway', character: 'Amelia Brand' },
    ],
    keywords: ['space', 'wormhole', 'time', 'survival', 'black hole'],
    maturity_rating: 'PG-13',
  },
  {
    id: 278,
    title: 'The Shawshank Redemption',
    overview: 'Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank State Penitentiary.',
    poster_path: '/lyQBXzOQSuE59IsHyhrp0qIiPAz.jpg',
    backdrop_path: '/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg',
    release_date: '1994-09-23',
    vote_average: 9.3,
    vote_count: 26000,
    genre_ids: [18],
    genres: [{ id: 18, name: 'Drama' }],
    runtime: 142,
    director: 'Frank Darabont',
    cast: [
      { id: 504, name: 'Tim Robbins', character: 'Andy Dufresne' },
      { id: 192, name: 'Morgan Freeman', character: 'Ellis Boyd "Red" Redding' },
    ],
    keywords: ['prison', 'hope', 'friendship', 'escape', 'redemption'],
    maturity_rating: 'R',
  },
  {
    id: 244786,
    title: 'Whiplash',
    overview: 'A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student\'s potential.',
    poster_path: '/7fn624j5lj3xTme2SgiLCeuedmO.jpg',
    backdrop_path: '/6bbZ6XyvgfjhQwbplnUh1LSj1iu.jpg',
    release_date: '2014-10-10',
    vote_average: 8.5,
    vote_count: 15000,
    genre_ids: [18, 10402],
    genres: [{ id: 18, name: 'Drama' }],
    runtime: 107,
    director: 'Damien Chazelle',
    cast: [
      { id: 1785339, name: 'Miles Teller', character: 'Andrew Neiman' },
      { id: 1813, name: 'J.K. Simmons', character: 'Terence Fletcher' },
    ],
    keywords: ['music', 'obsession', 'drums', 'ambition', 'abuse'],
    maturity_rating: 'R',
  },
  {
    id: 1891,
    title: 'The Empire Strikes Back',
    overview: 'The epic saga continues as Luke Skywalker, in hopes of defeating the evil Galactic Empire, learns the ways of the Jedi from an aging master.',
    poster_path: '/2l05cFWJacyIsTpsqSgH0wQXe4V.jpg',
    backdrop_path: '/vSNxIJkaBCxkKAzPfDMSGm3CGKN.jpg',
    release_date: '1980-05-21',
    vote_average: 8.7,
    vote_count: 18000,
    genre_ids: [12, 28, 878],
    genres: [{ id: 12, name: 'Adventure' }, { id: 28, name: 'Action' }, { id: 878, name: 'Sci-Fi' }],
    runtime: 124,
    director: 'Irvin Kershner',
    cast: [
      { id: 2, name: 'Mark Hamill', character: 'Luke Skywalker' },
      { id: 3, name: 'Harrison Ford', character: 'Han Solo' },
    ],
    keywords: ['darth vader', 'jedi', 'yoda', 'rebellion', 'empire'],
    maturity_rating: 'PG',
  },
  {
    id: 299534,
    title: 'Avengers: Endgame',
    overview: 'After the devastating events of Avengers: Infinity War, the universe is in ruins. Faced with a decimated Earth and half of all life wiped out, the Avengers must reassemble.',
    poster_path: '/or06FN3Dka5tukK1e9sl16pB3iy.jpg',
    backdrop_path: '/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg',
    release_date: '2019-04-26',
    vote_average: 8.4,
    vote_count: 26000,
    genre_ids: [28, 12],
    genres: [{ id: 28, name: 'Action' }, { id: 12, name: 'Adventure' }],
    runtime: 181,
    director: 'Anthony Russo',
    cast: [
      { id: 3223, name: 'Robert Downey Jr.', character: 'Tony Stark / Iron Man' },
      { id: 16828, name: 'Chris Evans', character: 'Steve Rogers / Captain America' },
    ],
    keywords: ['avengers', 'time travel', 'thanos', 'marvel', 'sacrifice'],
    maturity_rating: 'PG-13',
  },
  {
    id: 19404,
    title: 'Dilwale Dulhania Le Jayenge',
    overview: 'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being born in UK, is very strict about adherence to Indian values.',
    poster_path: '/2CAL2433ZeIihfX1Hb2139CX0pW.jpg',
    backdrop_path: '/90ez6ArvPSjR6GVDFKtZu1OjEbW.jpg',
    release_date: '1995-10-20',
    vote_average: 8.7,
    vote_count: 4000,
    genre_ids: [10749, 35],
    genres: [{ id: 10749, name: 'Romance' }, { id: 35, name: 'Comedy' }],
    runtime: 189,
    director: 'Aditya Chopra',
    cast: [
      { id: 11280, name: 'Shah Rukh Khan', character: 'Raj Malhotra' },
      { id: 313984, name: 'Kajol', character: 'Simran Singh' },
    ],
    keywords: ['bollywood', 'romance', 'india', 'family', 'love story'],
    maturity_rating: 'G',
  },
  {
    id: 496243,
    title: 'Parasite',
    overview: 'All unemployed, Ki-taek\'s family takes peculiar interest in the wealthy and glamorous Park family and begins to infiltrate their lives one by one.',
    poster_path: '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
    backdrop_path: '/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg',
    release_date: '2019-05-30',
    vote_average: 8.5,
    vote_count: 16000,
    genre_ids: [35, 18, 53],
    genres: [{ id: 35, name: 'Comedy' }, { id: 18, name: 'Drama' }, { id: 53, name: 'Thriller' }],
    runtime: 132,
    director: 'Bong Joon-ho',
    cast: [
      { id: 21165, name: 'Song Kang-ho', character: 'Ki-taek' },
    ],
    keywords: ['class', 'inequality', 'deception', 'korea', 'family'],
    maturity_rating: 'R',
  },
  {
    id: 38700,
    title: 'Bad Boys for Life',
    overview: 'Miami detectives Mike Lowry and Marcus Burnett try to take down the vicious leader of a Miami drug cartel who is after Lowry.',
    poster_path: '/y95lQLnuNKdPAzw9F9Ab8kJ80c3.jpg',
    backdrop_path: '/wGCMTRlSEg5TBmBpO7wIURkHCOP.jpg',
    release_date: '2020-01-17',
    vote_average: 7.2,
    vote_count: 7500,
    genre_ids: [28, 35, 80],
    genres: [{ id: 28, name: 'Action' }, { id: 35, name: 'Comedy' }, { id: 80, name: 'Crime' }],
    runtime: 124,
    director: 'Adil El Arbi',
    cast: [
      { id: 2157, name: 'Will Smith', character: 'Mike Lowry' },
      { id: 13159, name: 'Martin Lawrence', character: 'Marcus Burnett' },
    ],
    keywords: ['cop', 'action', 'buddy', 'miami', 'cartel'],
    maturity_rating: 'R',
  },
  {
    id: 346364,
    title: 'It',
    overview: 'In Derry, Maine in 1989, seven friends known as the Losers Club come face to face with an ancient shape-shifting evil that emerges from the sewer every 27 years to prey on the town\'s children.',
    poster_path: '/9E2y5Q7WlCCsy9lkDYF1QkNfLSx.jpg',
    backdrop_path: '/xqECHNvzbDL5I3iiOVUkVPJMSbc.jpg',
    release_date: '2017-09-08',
    vote_average: 7.3,
    vote_count: 15000,
    genre_ids: [27, 18],
    genres: [{ id: 27, name: 'Horror' }, { id: 18, name: 'Drama' }],
    runtime: 135,
    director: 'Andy Muschietti',
    cast: [
      { id: 1586047, name: 'Jaeden Martell', character: 'Bill Denbrough' },
    ],
    keywords: ['clown', 'fear', 'children', 'evil', 'supernatural'],
    maturity_rating: 'R',
  },
  {
    id: 769,
    title: 'GoodFellas',
    overview: 'The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito in the Italian-American crime syndicate.',
    poster_path: '/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg',
    backdrop_path: '/sw7mordbZxgITU877yTpZCud90M.jpg',
    release_date: '1990-09-19',
    vote_average: 8.7,
    vote_count: 12000,
    genre_ids: [18, 80],
    genres: [{ id: 18, name: 'Drama' }, { id: 80, name: 'Crime' }],
    runtime: 145,
    director: 'Martin Scorsese',
    cast: [
      { id: 1892, name: 'Ray Liotta', character: 'Henry Hill' },
      { id: 380, name: 'Robert De Niro', character: 'James Conway' },
    ],
    keywords: ['mafia', 'mob', 'crime', 'loyalty', 'betrayal'],
    maturity_rating: 'R',
  },
];

// ── Categorized rows ──────────────────────────────────────────────────────────
// endpoint fields are the future backend API routes for recommendation system

export const MOVIE_ROWS: MovieRow[] = [
  {
    title: 'Trending Now',
    movies: MOCK_MOVIES.filter(m => [27205, 155, 603, 475557, 299534].includes(m.id)),
    endpoint: '/api/recommendations/trending',
  },
  {
    title: 'Top Rated',
    movies: MOCK_MOVIES.filter(m => m.vote_average >= 8.7),
    endpoint: '/api/recommendations/top-rated',
  },
  {
    title: 'Action & Thriller',
    movies: MOCK_MOVIES.filter(m => m.genre_ids.some(g => [28, 53].includes(g))),
    endpoint: '/api/recommendations/genre/action',
  },
  {
    title: 'Crime & Drama',
    movies: MOCK_MOVIES.filter(m => m.genre_ids.some(g => [18, 80].includes(g))),
    endpoint: '/api/recommendations/genre/drama',
  },
  {
    title: 'Sci-Fi & Adventure',
    movies: MOCK_MOVIES.filter(m => m.genre_ids.some(g => [878, 12, 14].includes(g))),
    endpoint: '/api/recommendations/genre/scifi',
  },
  {
    title: 'Award Winners',
    movies: MOCK_MOVIES.filter(m => [278, 238, 496243, 244786, 680].includes(m.id)),
    endpoint: '/api/recommendations/award-winners',
  },
];

// Featured movie for the hero banner (first in trending)
export const FEATURED_MOVIE = MOCK_MOVIES.find(m => m.id === 27205)!;
